[package]
name = "lddfrom"
version = "0.1.1"
edition = "2021"
authors = ["Hunter Kirk"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
